all:
	gcc bublesort.c -o bublesort -g -lm
	gcc quicksort.c -o quicksort -g -lm
	gcc merge.c -o merge -g -lm
quicksort:
	gcc quicksort.c -o quicksort -g -lm
bublesort:
	gcc bublesort.c -o bublesort -g -lm
merge:
	gcc bublesort.c -o bublesort -g -lm
